import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Privacy policy for Root Cause Analytics Pty Ltd, bound by the Australian Privacy Principles under the Privacy Act 1988 (Cth).",
  alternates: { canonical: "/privacy" },
  robots: { index: false },
};

export default function PrivacyPage() {
  return (
    <>
      <section className="page-hero">
        <p className="kicker rv-auto">Legal · last updated 14 May 2026</p>
        <h1 className="rv-auto d1">Privacy Policy</h1>
      </section>
      <section className="section">
        <div className="prose rv">
          <p>
            Root Cause Analytics Pty Ltd operates this website and product
            line. We are bound by the Australian Privacy Principles (APPs)
            under the Privacy Act 1988 (Cth). Direct enquiries or complaints to{" "}
            <a href="mailto:jack.webb@rootcauseanalytics.com.au">
              jack.webb@rootcauseanalytics.com.au
            </a>
            .
          </p>
          <p>
            <b>What we collect.</b> Name, work email, organisation, role and
            message content when you contact us. Technical metadata such as IP
            address and browser information through analytics cookies. We do
            not collect, store or process any clinical, claims, underwriting or
            financial data from website visitors.
          </p>
          <p>
            <b>How we use it.</b> To respond to enquiries, deliver requested
            materials, improve the site through aggregate analytics, and meet
            our obligations under Australian law.
          </p>
          <p>
            <b>Our products.</b> The extraction app runs self-hosted inside
            your infrastructure. Patient data, documents and extracted output
            remain entirely within your environment. We cannot access your
            documents. Our synthetic libraries are generated by a deterministic
            pipeline from curated case files and phrase banks. No real
            operational data is involved.
          </p>
          <p>
            <b>Third-party services.</b> The website is hosted on Vercel.
            Analytics, where enabled, are aggregate only.
          </p>
          <p>
            <b>Your rights.</b> You can request a copy of your personal
            information, request corrections, and request deletion subject to
            legal requirements. You can complain to the Office of the
            Australian Information Commissioner.
          </p>
          <p>
            <b>Retention.</b> Contact submissions are retained for as long as
            the related commercial relationship is active, plus seven years for
            tax and accounting purposes.
          </p>
        </div>
      </section>
    </>
  );
}
