import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import FilmStrip from "@/components/FilmStrip";
import TrialTable from "@/components/TrialTable";
import evidence from "@/lib/evidence.json";

export const metadata: Metadata = {
  title: "Root Cause Analytics · Ten thousand PDFs in. One clean table out.",
  description:
    "RCA turns large quantities of PDFs and paper documents into clean, catalogued tables, and generates realistic synthetic Australian documents for AI training and evaluation. Sydney, Australia.",
  alternates: { canonical: "/" },
};

export default function HomePage() {
  const v2 = evidence.v2Benchmark;
  const trial = evidence.liveTrial;
  const trialDate = new Date(trial.date).toLocaleDateString("en-AU", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

  return (
    <>
      <section className="hero">
        <div>
          <h1 className="rv-auto d1">
            Ten thousand PDFs in. <span className="hl">One clean table</span>{" "}
            out.
          </h1>
          <p className="sub rv-auto d2">
            RCA turns large quantities of PDFs and paper documents into{" "}
            <b>clean, catalogued tables</b>. Extract the key values, report on
            them, and find the patterns that were stuck in filing cabinets.
            More capable than standard digitisation software,{" "}
            <b>at a fraction of the price</b>.
          </p>
          <div className="ctas rv-auto d3">
            <Link className="btn btn-gold" href="/document-library">
              See the Document Library
            </Link>
            <Link className="btn btn-ghost" href="/document-generator">
              See the Generator
            </Link>
          </div>
          <p className="hero-note rv-auto d3">
            Both apps run on your own hardware and work offline. Every
            extracted value carries a confidence score you can check.
          </p>
        </div>

        <div className="specimen-wrap rv-auto d2">
          <div className="stamp">Synthetic · No PHI</div>
          <div className="doc">
            <Image
              src="/specimens/spec-treatment-plan-1.png"
              alt="Synthetic staged care plan generated by the RCA engine"
              width={620}
              height={877}
              priority
              style={{ width: "100%", height: "auto" }}
            />
            <span className="mk m1" aria-hidden="true" style={{ left: "26.59%", top: "12.9%", width: "17.8%", height: "1.71%" }} />
            <span className="mk m2" aria-hidden="true" style={{ left: "66.48%", top: "15.07%", width: "10.44%", height: "1.4%" }} />
            <span className="mk m3" aria-hidden="true" style={{ left: "26.59%", top: "20.75%", width: "8.9%", height: "1.4%" }} />
            <span className="mk m4" aria-hidden="true" style={{ left: "33.63%", top: "35.28%", width: "28.68%", height: "1.63%" }} />
            <div className="panel">
              <div className="panel-head">
                <span>Extracted fields</span>
              </div>
              <div className="phead" aria-hidden="true">
                <span>Field</span>
                <span>Extracted value</span>
                <span className="pc">Accuracy</span>
              </div>
              <div className="prow p1">
                <span className="f">patient_name</span>
                <span className="v">Sarah Rebecca Wright</span>
                <span className="c">0.99</span>
              </div>
              <div className="prow p2">
                <span className="f">medicare_no</span>
                <span className="v">6600 13384 1</span>
                <span className="c">0.98</span>
              </div>
              <div className="prow p3">
                <span className="f">plan_date</span>
                <span className="v">26/06/2026</span>
                <span className="c">0.97</span>
              </div>
              <div className="prow p4 warn">
                <span className="f">diagnosis</span>
                <span className="v">Bilateral knee OA</span>
                <span className="c">0.84</span>
              </div>
            </div>
          </div>
          <p className="spec-cap" style={{ marginTop: 16 }}>
            Specimen AUS-TRN-0001, generated by the RCA engine. All patient
            and clinic details are fully synthetic.
          </p>
        </div>
      </section>

      <section className="products">
        <div className="sec-head rv">
          <h2>What we build</h2>
          <span>The catalogue · index of holdings</span>
        </div>
        <div className="prod-grid">
          <div className="prod rv">
            <span className="no">№ 01</span>
            <h3>RCA Document Library</h3>
            <div className="what">For your real documents</div>
            <p>
              Point it at your PDFs and scans. It reads them, extracts the
              fields you care about, scores its own confidence on every value,
              and builds a <b>clean table you can search and export</b>.
            </p>
            <ul>
              <li>
                {v2.accuracyPct}% field accuracy on OCR-only extraction (V2
                benchmark, {v2.fields} fields)
              </li>
              <li>Offline-first: OCR, extraction, search and export without internet</li>
              <li>Confidence built from four visible factors, not a black box</li>
              <li>Optional AI validation layer that never overwrites OCR results</li>
              <li>Costs a fraction of a standard digitisation contract</li>
            </ul>
            <Link className="go" href="/document-library">
              Open the Document Library →
            </Link>
          </div>
          <div className="prod alt rv d1">
            <span className="no">№ 02</span>
            <h3>RCA Document Generator</h3>
            <div className="what">For safe AI training and testing</div>
            <p>
              Realistic synthetic Australian documents for training and
              evaluating AI, with <b>complete ground truth on every field</b>.
              No real patient anywhere in the pipeline.
            </p>
            <ul>
              <li>45 medical document types across 81 clinical case archetypes</li>
              <li>Deterministic: same seed, byte-identical PDFs and ground truth</li>
              <li>Insurance packs, including red-flag packs with planted inconsistencies</li>
              <li>Fully offline: about 5,000 documents in 5 minutes, no LLM calls</li>
              <li>Valid Medicare and provider formats, NSW addresses, real structure</li>
            </ul>
            <Link className="go" href="/document-generator">
              Open the Document Generator →
            </Link>
          </div>
        </div>
      </section>

      <FilmStrip />

      <section className="band">
        <Image
          className="mark"
          src="/brand/logo-mark-paper.png"
          alt=""
          width={500}
          height={500}
        />
        <div className="band-inner">
          <h2 className="rv">
            Numbers from our published benchmarks, <em>misses included.</em>
          </h2>
          <div className="stat rv d1">
            <span className="mono">Extraction</span>
            <b>{v2.accuracyPct}%</b>
            <span>
              field accuracy on OCR-only extraction. V2 benchmark, {v2.fields}{" "}
              fields, no AI assistance
            </span>
          </div>
          <div className="stat rv d2">
            <span className="mono">Generation</span>
            <b>45 + 81</b>
            <span>
              medical document types and internally consistent clinical case
              archetypes
            </span>
          </div>
          <div className="stat rv d3">
            <span className="mono">Speed</span>
            <b>5 min</b>
            <span>
              to generate about 5,000 documents, fully offline, with ground
              truth
            </span>
          </div>
        </div>
      </section>

      <section className="evidence">
        <div className="sec-head rv">
          <h2>We publish our misses.</h2>
          <span>Evidence · live trial {trialDate}</span>
        </div>
        <div className="ev-grid">
          <div className="rv d1">
            <p>
              Most vendors quote a single glossy accuracy number. We publish
              the full run log instead: every field, every document, including
              the ones we got wrong.{" "}
              <b>When a model fails, we score it zero and say so.</b> Two dense
              flow sheets broke the output limit on the smaller model. They are
              in the table, not under the rug.
            </p>
            <p className="foot">
              Run {trial.dataset} · {trialDate}, Sydney time
              <br />
              Total API spend for this run: A${trial.totalSpendAud}*
              <br />
              *Yes, under two dollars. Testing with ground truth is cheap.
              Guessing is expensive.
            </p>
            <p style={{ marginTop: 22 }}>
              <Link className="btn btn-ghost" href="/evidence">
                See the evidence →
              </Link>
            </p>
          </div>
          <div className="rv d2 table-scroll">
            <TrialTable />
          </div>
        </div>
      </section>

      <section className="founder">
        <div className="founder-inner rv">
          <h2>
            I started RCA because I had this problem myself and could not find
            a good solution on the market. Most businesses sit on thousands of
            PDFs and paper documents they cannot use. RCA extracts the key
            values, builds a clean table for cataloguing them, and gives you
            metrics and patterns that were locked in paper. It does what the
            standard digitisation vendors do,{" "}
            <em>with more capability, at a fraction of the price.</em>
          </h2>
          <div className="sig">
            <span className="name">Jack Webb</span>
            <span className="role">
              Founder, Root Cause Analytics
              <br />
              Sydney, NSW
            </span>
          </div>
        </div>
      </section>

      <section className="cta">
        <div className="cta-card rv">
          <div>
            <h2>
              See the quality before you <em>spend a dollar.</em>
            </h2>
            <p>
              Request a free preview pack: real sample documents with ground
              truth included, so your team can evaluate hands-on.
            </p>
          </div>
          <div className="cta-actions">
            <Link className="btn btn-gold" href="/contact">
              Request a preview pack
            </Link>
            <Link className="btn btn-paper" href="/contact">
              Talk to Jack →
            </Link>
            <span className="mono-note">
              Replies within one business day, Sydney time.
            </span>
          </div>
        </div>
      </section>
    </>
  );
}
