'use client'

import { useEffect } from 'react'
import Link from 'next/link'
import Navigation from '@/components/navigation'
import Footer from '@/components/footer'

function useScrollAnimation() {
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((e) => { if (e.isIntersecting) e.target.classList.add('visible') }),
      { threshold: 0.1 }
    )
    document.querySelectorAll('.animate-on-scroll').forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [])
}

const LAST_UPDATED = '14 May 2026'

export default function TermsPage() {
  useScrollAnimation()

  return (
    <>
      <Navigation />
      <main id="main-content">
        <section className="pt-24 pb-12 bg-gradient-to-br from-[#1E3A8A] to-[#0D9488]" aria-label="Terms hero">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 text-balance">
              Terms of Service
            </h1>
            <p className="text-sm text-white/70">
              Last updated: {LAST_UPDATED}
            </p>
          </div>
        </section>

        <section className="py-16 bg-white" aria-label="Terms content">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <article className="prose-rca animate-on-scroll">
              <p className="text-slate-600 leading-relaxed mb-6">
                These Terms of Service ("Terms") govern your use of the Root Cause Analytics website and the products and services made available by Root Cause Analytics Pty Ltd (we, us, our). By using this website, requesting a preview pack, ordering a library, or installing RCA Extract from the Snowflake Marketplace, you agree to these Terms.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">1. Products covered by these Terms</h2>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-6 flex flex-col gap-1">
                <li><strong>RCA Extract</strong> - a Snowflake Native App for healthcare document extraction. Distributed through the Snowflake Marketplace (listing GZSUZU1HJP). Snowflake's terms also apply to RCA Extract usage and billing.</li>
                <li><strong>RCA Insurance Library</strong> - synthetic commercial P&amp;C submission packs.</li>
                <li><strong>RCA Medical Library</strong> - synthetic Australian medical training documents.</li>
                <li><strong>RCA Benchmark Packs</strong> - smaller curated paid packs (including the Insurance QA Sprint Pack).</li>
                <li><strong>RCA Custom Libraries</strong> - bespoke synthetic libraries scoped per order.</li>
              </ul>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">2. Synthetic-only restriction</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                All documents in the RCA Insurance Library, RCA Medical Library, and RCA Benchmark Packs are synthetic. They are generated by a deterministic Python pipeline from curated case files and phrase banks. No real patient, claimant, broker, insurer, or customer data is held, transmitted, or stored anywhere in the generator or the libraries. Every PDF carries a visible synthetic disclaimer on every page.
              </p>
              <p className="text-slate-700 font-medium mb-3">
                You agree not to use the synthetic libraries, or any documents within them, for:
              </p>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-6 flex flex-col gap-1">
                <li>Clinical care, diagnosis, medical coding, billing, or any clinical decision-making.</li>
                <li>Insurance underwriting, claims handling, claims investigation, or any policy or claim decision.</li>
                <li>Regulatory submissions, accounting, tax, audit, identity verification, or any legal proceeding.</li>
                <li>Any purpose where the documents are presented or treated as real records, real customers, real patients, real brokers, real insurers, or real medical or insurance professionals.</li>
              </ul>
              <p className="text-slate-600 leading-relaxed mb-6">
                You agree not to strip or alter the visible synthetic disclaimer on any page of any document we provide.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">3. License to the libraries and packs</h2>
              <p className="text-slate-600 leading-relaxed mb-3">
                Subject to the restrictions in section 2, when you receive or purchase a library or a pack, we grant you a non-exclusive, non-transferable license to:
              </p>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-6 flex flex-col gap-1">
                <li>Use the documents and accompanying ground truth, bounding boxes and manifests to train, fine-tune, evaluate, or QA document AI models.</li>
                <li>Use the documents to stress-test extraction pipelines against varied layouts and scanned input.</li>
                <li>Use the documents to demonstrate an internal extraction system to your stakeholders or to run a procurement evaluation.</li>
                <li>Redistribute the documents within your organisation for the above purposes.</li>
              </ul>
              <p className="text-slate-600 leading-relaxed mb-6">
                You may not redistribute the libraries publicly, host the documents on a public-facing site without our written permission, or resell the libraries.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">4. Pricing and payment</h2>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-6 flex flex-col gap-1">
                <li>The Insurance 2-pack preview is provided free of charge for qualified prospects.</li>
                <li>The Medical 25-doc review pack is provided free of charge for qualified prospects.</li>
                <li>The Insurance QA Sprint Pack is AUD $2,500 fixed, delivered within 48 to 72 hours of order confirmation.</li>
                <li>Larger libraries (Insurance, Medical) and custom variants are priced per scope and invoiced separately.</li>
                <li>RCA Extract pricing depends on volume, deployment shape, and SLA. Contact us for a quote. Billing for RCA Extract is handled through the Snowflake Marketplace.</li>
              </ul>
              <p className="text-slate-600 leading-relaxed mb-6">
                Payment terms are stated on each invoice. Australian dollars (AUD) unless otherwise stated.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">5. RCA Extract on the Snowflake Marketplace</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                RCA Extract is distributed as a Snowflake Native App through the Snowflake Marketplace. The Marketplace terms, Snowflake's privacy notice, and the relevant Snowflake Native App framework terms also apply. RCA Extract runs inside your own Snowflake account. Patient data and extracted output remain entirely within your Snowflake environment. Root Cause Analytics does not have access to your documents or extracted data.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">6. Intellectual property</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                Root Cause Analytics retains all intellectual property rights in the generator, the libraries, the schemas, the documentation, the website, and the brand. You retain ownership of any models, pipelines, or analytics you build using the libraries, subject to the license in section 3.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">7. Warranties and exclusions</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                The libraries and the website are provided on an "as is" basis. To the maximum extent permitted by law, we exclude all warranties, conditions and representations other than those that cannot be excluded under Australian Consumer Law. We do not warrant that the documents are statistically representative of any specific hospital, broker, insurer book, jurisdiction, or population. We do not warrant any specific extraction accuracy without a published benchmark methodology and corresponding results.
              </p>
              <p className="text-slate-600 leading-relaxed mb-6">
                Nothing in these Terms excludes, restricts, or modifies any consumer guarantees under the Australian Consumer Law that cannot be lawfully excluded.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">8. Liability</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                To the maximum extent permitted by law, our total aggregate liability to you for any claim arising out of or in connection with these Terms, the libraries, or the website, is limited to the amount you have paid us in the twelve months preceding the claim. We are not liable for any indirect, consequential, or special loss, including loss of profits, loss of revenue, loss of goodwill, or loss of data.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">9. Indemnity</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                You agree to indemnify us against any claim arising out of your breach of section 2 (synthetic-only restriction), including any claim that arises from you using a synthetic document as if it were a real record.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">10. Termination</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                We may terminate or suspend your access to the website, the libraries, or RCA Extract if you breach these Terms. On termination, the licenses granted in section 3 end and you must stop using the libraries.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">11. Changes to these Terms</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                We may update these Terms from time to time. The Last updated date at the top of this page reflects the most recent change. Material changes will be notified through the website. Continued use of the website or the products after a change takes effect constitutes acceptance of the updated Terms.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">12. Governing law</h2>
              <p className="text-slate-600 leading-relaxed mb-6">
                These Terms are governed by the laws of New South Wales, Australia. Each party submits to the non-exclusive jurisdiction of the courts of New South Wales.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-3">13. Contact</h2>
              <p className="text-slate-600 leading-relaxed mb-3">
                Root Cause Analytics Pty Ltd<br />
                Sydney, NSW, Australia<br />
                <a href="mailto:jack.webb@rootcauseanalytics.com.au" className="text-[#0D9488] hover:underline">jack.webb@rootcauseanalytics.com.au</a>
              </p>

              <hr className="my-10 border-slate-200" />
              <p className="text-sm text-slate-500 leading-relaxed">
                See also: <Link href="/privacy" className="text-[#0D9488] hover:underline">Privacy Policy</Link> and <Link href="/security" className="text-[#0D9488] hover:underline">Security Notice</Link>.
              </p>
            </article>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
