// Downloads latin and latin-ext woff2 subsets for the site fonts from Google
// Fonts and writes a self-hosted app/fonts.css with font-display: swap.
// Run once at setup: node scripts/fetch-fonts.mjs
import { writeFile, mkdir } from "node:fs/promises";
import path from "node:path";

const CSS_URL =
  "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,550;0,9..144,650;1,9..144,450&family=Hanken+Grotesk:wght@400;500;600;700&family=IBM+Plex+Mono:ital,wght@0,400;0,500;0,600;1,400&family=Caveat:wght@500&display=swap";
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36";

const root = path.resolve(new URL(".", import.meta.url).pathname, "..");
const fontDir = path.join(root, "public", "fonts");
await mkdir(fontDir, { recursive: true });

const css = await (await fetch(CSS_URL, { headers: { "User-Agent": UA } })).text();

// Split into comment-labelled blocks, keep latin and latin-ext only.
const blocks = css.split(/\/\* ([a-z-]+) \*\//).slice(1);
let out = "/* Self-hosted fonts. Generated by scripts/fetch-fonts.mjs. */\n";
const seen = new Set();
for (let i = 0; i < blocks.length; i += 2) {
  const subset = blocks[i];
  let block = blocks[i + 1];
  if (subset !== "latin" && subset !== "latin-ext") continue;
  const family = block.match(/font-family: '([^']+)'/)[1];
  const style = block.match(/font-style: (\w+)/)[1];
  const weight = block.match(/font-weight: ([\d ]+)/)[1].trim().replace(/ /g, "-");
  const url = block.match(/url\((https:[^)]+)\)/)[1];
  const name = `${family.toLowerCase().replace(/ /g, "-")}-${style}-${weight}-${subset}.woff2`;
  if (!seen.has(name)) {
    seen.add(name);
    const buf = Buffer.from(await (await fetch(url)).arrayBuffer());
    await writeFile(path.join(fontDir, name), buf);
    console.log(`saved ${name} (${buf.length} bytes)`);
  }
  out += `/* ${subset} */` + block.replace(url, `/fonts/${name}`);
}
await writeFile(path.join(root, "app", "fonts.css"), out);
console.log("wrote app/fonts.css");
