'use client'

import { useEffect } from 'react'
import Link from 'next/link'
import { Shield, Lock, Database, FileText, CheckCircle, AlertCircle } from 'lucide-react'
import Navigation from '@/components/navigation'
import Footer from '@/components/footer'

function useScrollAnimation() {
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => entries.forEach((e) => { if (e.isIntersecting) e.target.classList.add('visible') }),
      { threshold: 0.1 }
    )
    document.querySelectorAll('.animate-on-scroll').forEach((el) => observer.observe(el))
    return () => observer.disconnect()
  }, [])
}

const LAST_UPDATED = '14 May 2026'

export default function SecurityPage() {
  useScrollAnimation()

  return (
    <>
      <Navigation />
      <main id="main-content">
        <section className="pt-24 pb-12 bg-gradient-to-br from-[#1E3A8A] to-[#0D9488]" aria-label="Security hero">
          <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
            <h1 className="text-4xl sm:text-5xl font-bold text-white mb-4 text-balance">
              Security Notice
            </h1>
            <p className="text-sm text-white/70">
              Last updated: {LAST_UPDATED}
            </p>
          </div>
        </section>

        <section className="py-16 bg-white" aria-label="Security content">
          <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
            <article className="prose-rca animate-on-scroll">
              <p className="text-slate-600 leading-relaxed mb-10">
                Root Cause Analytics Pty Ltd ("we", "us", "our") takes security seriously. This notice describes how we secure the products we ship and the operational practices we follow. For privacy questions, see the <Link href="/privacy" className="text-[#0D9488] hover:underline">Privacy Policy</Link>.
              </p>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-2 mb-4">RCA Extract on Snowflake</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                RCA Extract is delivered as a Snowflake Native App through the Snowflake Marketplace (listing GZSUZU1HJP). The product runs entirely inside the customer's own Snowflake account.
              </p>
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-5 mb-8">
                <ul className="flex flex-col gap-3">
                  {[
                    { icon: Shield, text: 'Patient data, documents and extracted output remain entirely within your Snowflake environment.' },
                    { icon: Lock, text: 'Root Cause Analytics does not have access to your documents or the extracted data.' },
                    { icon: CheckCircle, text: 'Your existing Snowflake security controls, audit logs and access policies apply to every document processed.' },
                    { icon: Database, text: 'No external API calls. No third-party data processors involved in extraction.' },
                    { icon: FileText, text: 'Encryption at rest and in transit, provided by Snowflake.' },
                  ].map(({ icon: Icon, text }) => (
                    <li key={text} className="flex items-start gap-3 text-sm text-slate-700">
                      <Icon size={16} className="text-[#0D9488] mt-0.5 shrink-0" />
                      <span className="leading-relaxed">{text}</span>
                    </li>
                  ))}
                </ul>
              </div>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-4">Synthetic training document libraries</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                The RCA Insurance Library, RCA Medical Library and RCA Benchmark Packs are synthetic. They are generated by a deterministic Python pipeline from curated case files and phrase banks. No real patient, claimant, broker, insurer, or customer data is held, transmitted or stored anywhere in the generator or the libraries.
              </p>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-8 flex flex-col gap-1">
                <li>Every PDF carries a visible synthetic disclaimer on every page.</li>
                <li>Libraries are delivered as direct downloads. We do not introduce third-party file-share processors unless the customer requests one and a data agreement is in place.</li>
                <li>The libraries are not licensed for clinical, claims, underwriting, accounting, regulatory or legal use. See the <Link href="/terms" className="text-[#0D9488] hover:underline">Terms of Service</Link>.</li>
              </ul>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-4">Website</h2>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-8 flex flex-col gap-1">
                <li>HTTPS everywhere. HSTS enabled.</li>
                <li>Hosted on Vercel with their default security controls.</li>
                <li>Static site generation reduces server-side attack surface.</li>
                <li>Contact form submissions are emailed to the founder inbox; no public-facing customer database is exposed.</li>
                <li>Analytics via Google Analytics 4 (aggregate metrics only).</li>
              </ul>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-4">Operational practices</h2>
              <ul className="list-disc pl-6 text-slate-600 leading-relaxed mb-8 flex flex-col gap-1">
                <li>Source code stored in a private GitHub repository under access controls.</li>
                <li>Two-factor authentication enabled on all administrative accounts (GitHub, Vercel, Snowflake Marketplace publisher account, email).</li>
                <li>Production deployments are gated on the main branch and trigger an immediate auditable build on Vercel.</li>
                <li>Credentials and secrets are managed via Vercel environment variables. None are committed to source.</li>
                <li>No production access from personal mobile devices.</li>
              </ul>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-4">Reporting a vulnerability</h2>
              <p className="text-slate-600 leading-relaxed mb-4">
                If you discover a security issue affecting our website, our products, or the synthetic libraries, please report it to <a href="mailto:jack.webb@rootcauseanalytics.com.au" className="text-[#0D9488] hover:underline">jack.webb@rootcauseanalytics.com.au</a>.
              </p>
              <div className="bg-[#CCFBF1]/40 border border-[#0D9488]/30 rounded-xl p-5 mb-8">
                <div className="flex items-start gap-3">
                  <AlertCircle size={18} className="text-[#0D9488] mt-0.5 shrink-0" />
                  <div>
                    <p className="text-sm text-slate-700 leading-relaxed mb-2 font-semibold">
                      Coordinated disclosure
                    </p>
                    <p className="text-sm text-slate-700 leading-relaxed">
                      Please give us a reasonable opportunity to investigate and resolve the issue before publishing details. We will acknowledge your report within five business days (AEST).
                    </p>
                  </div>
                </div>
              </div>

              <h2 className="text-xl font-bold text-[#1E3A8A] mt-10 mb-4">Customer security questionnaires</h2>
              <p className="text-slate-600 leading-relaxed mb-8">
                We respond to security and procurement questionnaires from prospective customers. Email <a href="mailto:jack.webb@rootcauseanalytics.com.au" className="text-[#0D9488] hover:underline">jack.webb@rootcauseanalytics.com.au</a> with the questionnaire attached and a reasonable response window.
              </p>

              <hr className="my-10 border-slate-200" />
              <p className="text-sm text-slate-500 leading-relaxed">
                See also: <Link href="/privacy" className="text-[#0D9488] hover:underline">Privacy Policy</Link> and <Link href="/terms" className="text-[#0D9488] hover:underline">Terms of Service</Link>.
              </p>
            </article>
          </div>
        </section>
      </main>
      <Footer />
    </>
  )
}
